//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.LocalizationSystem
{
    
    
    public class LocalizationKeys
    {
        
        public const string settingsTitle = "settingsTitle";
        
        public const string gameOver = "gameOver";
        
        public const string about = "about";
        
        public const string @continue = "continue";
        
        public const string review = "review";
        
        public const string restart = "restart";
        
        public const string leaderboard = "leaderboard";
        
        public const string feedback = "feedback";
        
        public const string sound = "sound";
        
        public const string gamesPlayed = "gamesPlayed";
        
        public const string richestScore = "richestScore";
        
        public const string statistics = "statistics";
        
        public const string Loading = "Loading";
        
        public const string moreGames = "moreGames";
        
        public const string free = "free";
        
        public const string timeOut = "timeOut";
        
        public const string gift = "gift";
        
        public const string LevelPassed = "LevelPassed";
        
        public const string Level = "Level";
        
        public const string LevelFail = "LevelFail";
        
        public const string flyingControl = "flyingControl";
        
        public const string moveSpeed = "moveSpeed";
        
        public const string health = "health";
        
        public const string forAd = "forAd";
        
        public const string tapToThrow = "tapToThrow";
        
        public const string skipLevel = "skipLevel";
        
        public const string claim = "claim";
    }
}
